[project]
name = "blackjack-rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gymnasium>=1.1.1",
    "stable-baselines3[extra]>=2.6.0",
]
